name: Path lister
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      # - name: Lint
      #   run: |
      #     pip install flake8
      #     flake8 main.py

      - name: Path list
        id: pl
        uses: Rishabh510/Path-lister-action@master
        # with:
        #   path: "tests/invalid.yaml"
      - name: Output file
        run: |
          python main.py
